// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiiHrmjtCIqxxKndBCSKz_eBfb9EjZUtg',
    appId: '1:668279913310:web:850b96dd648c5bee7dedcf',
    messagingSenderId: '668279913310',
    projectId: 'p-k-123-construction',
    authDomain: 'p-k-123-construction.firebaseapp.com',
    storageBucket: 'p-k-123-construction.firebasestorage.app',
    measurementId: 'G-LCVN085W0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcjRGGVr1CEzIrzCiF_KhFvdgTHjxtcDw',
    appId: '1:668279913310:android:c05817667906a0857dedcf',
    messagingSenderId: '668279913310',
    projectId: 'p-k-123-construction',
    storageBucket: 'p-k-123-construction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SkDsdhB71dRnRV5jvt2y-CFs8iAO0zI',
    appId: '1:668279913310:ios:248fbe31290583cd7dedcf',
    messagingSenderId: '668279913310',
    projectId: 'p-k-123-construction',
    storageBucket: 'p-k-123-construction.firebasestorage.app',
    iosBundleId: 'com.example.pkManuConstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SkDsdhB71dRnRV5jvt2y-CFs8iAO0zI',
    appId: '1:668279913310:ios:248fbe31290583cd7dedcf',
    messagingSenderId: '668279913310',
    projectId: 'p-k-123-construction',
    storageBucket: 'p-k-123-construction.firebasestorage.app',
    iosBundleId: 'com.example.pkManuConstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiiHrmjtCIqxxKndBCSKz_eBfb9EjZUtg',
    appId: '1:668279913310:web:b8f3883d8869fb1a7dedcf',
    messagingSenderId: '668279913310',
    projectId: 'p-k-123-construction',
    authDomain: 'p-k-123-construction.firebaseapp.com',
    storageBucket: 'p-k-123-construction.firebasestorage.app',
    measurementId: 'G-2E570YZNMJ',
  );
}
