import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';
import 'features/auth/login_screen.dart';
import 'features/dashboard/dashboard_screen.dart';

void main() async {
  // 1. Mandatory for Firebase initialization
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with the options generated by flutterfire configure
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const PKConstructionApp());
}

class PKConstructionApp extends StatelessWidget {
  const PKConstructionApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'P.K. Construction',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      // StreamBuilder watches for login status changes automatically
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // If connection is still waiting, show a loading spinner
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }

          // If the user is logged in, send them to the Dashboard
          if (snapshot.hasData) {
            return const DashboardScreen();
          }

          // Otherwise, show the Login screen
          return LoginScreen();
        },
      ),
    );
  }
}
